apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql:5.7
    name: mysql-pod
    envFrom:
    - secretRef:        
       name: db-secret  
    volumeMounts:
    - name: mysql-initdb
      mountPath: /docker-entrypoint-initdb.d
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql  
  volumes:
  - name: mysql-initdb
    configMap:
      name: mysql-initdb-config             
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim      
  dnsPolicy: ClusterFirst
  restartPolicy: Always

