apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin-svc
  name: phpmyadmin-svc
spec:
  ports:
  - name: phpmyadmin-svc 
    port: 8099
    protocol: TCP
    targetPort: 80
    nodePort: 30248
  selector:
    run: phpadmin-pod
  type: NodePort
